#!/usr/bin/env python3
"""Analyses added for the camera-ready version (CELDA 2026 reviews, Sept 2026).

Reads out/items_merged.csv (written by analyze.py) and the raw score exports, and writes
out/camera_ready.md. Run analyze.py first.

  1. Agreement on collapsed schemes (lower vs higher order; remember vs the rest).
  2. Per-exam agreement and per-exam correlations with facility.
  3. Uncertainty that reflects student sampling as well as item sampling: a two-stage
     bootstrap (students resampled within exam, then items within exam).
  4. Writes out/responses_long.csv for the mixed logistic model in camera_ready_glmm.R
     (exam as fixed effect, crossed random intercepts for students and items, lme4).
  5. Binomial (Wilson) uncertainty of item facility.
  6. KR-20 with a student bootstrap interval, and without the items rater B flagged
     for weak distractors; item-rest correlation of flagged vs other items.
Run:  uv run python camera_ready.py
"""
from __future__ import annotations

import csv
import glob
import json
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats
from sklearn.metrics import cohen_kappa_score
from statsmodels.stats.proportion import proportion_confint

HERE = Path(__file__).resolve().parent
OUT = HERE / "out"
RNG = np.random.default_rng(20260925)
RENAME = {"Exam 2": "Exam 1", "Midterm 3": "Exam 2", "Final Exam": "Exam 3"}
EXAMS = ["Exam 1", "Exam 2", "Exam 3"]
B = 2000

md: list[str] = []


def say(s: str = "") -> None:
    md.append(s)
    print(s)


df = pd.read_csv(OUT / "items_merged.csv")

# ---------------------------------------------------------------- responses (students x items per exam)
data = json.loads((HERE / "data" / "export.json").read_text())
exam_for_file = {e["result_file"]: e["name"] for e in data["exams"]}
X = {}  # exam -> (students x items array, item numbers)
for f in sorted(glob.glob(str(HERE.parent / "data" / "result_export_*.csv"))):
    exam = RENAME[exam_for_file[Path(f).name]]
    with open(f, encoding="utf-8-sig", newline="") as fh:
        recs = list(csv.DictReader(fh))
    M = defaultdict(dict)
    for r in recs:
        M[r["UserId"]][int(r["QuestionNo"])] = float(r["AutoGradedScore"])
    Q = sorted({q for s in M.values() for q in s})
    X[exam] = (np.array([[M[s][q] for q in Q] for s in M]), Q, list(M))

# rows of df in the same order as the columns of X[exam]
IDX = {e: [df.index[(df.exam == e) & (df.no == q)][0] for q in X[e][1]] for e in EXAMS}

# items rater B flagged for weak distractors (codes use export exam names)
from comment_codes import CODES
flag = {(e, n) for (e, n, who), th in CODES.items() if who == "B" and "distractors" in th}
df["flag"] = [(o, int(n)) in flag for o, n in zip(df.exam_orig, df.no)]

# ================================================================ 1. collapsed agreement
BLOOM = {"Rater A": "A_bloom_i", "Rater B": "B_bloom_i", "Gemini self": "llm_bloom_i",
         "Fable instr.": "F_bloom_i_n", "Fable bare": "F_bloom_b_n", "Gemini cold": "G_bloom_i_n"}
PAIRS = [("Rater A", "Rater B"), ("Rater A", "Gemini self"), ("Rater B", "Gemini self"),
         ("Fable instr.", "Rater A"), ("Fable instr.", "Rater B"), ("Fable instr.", "Gemini self"),
         ("Gemini cold", "Rater A"), ("Gemini cold", "Rater B"), ("Gemini cold", "Gemini self"),
         ("Gemini cold", "Fable instr.")]
SCHEMES = {"six levels": lambda v: v,
           "lower/higher (rem+und | app+)": lambda v: (v >= 2).astype(int),
           "remember | rest": lambda v: (v >= 1).astype(int)}


def kappa_strat_ci(a, b, ex):
    """κ with a bootstrap over items resampled within exam."""
    k = cohen_kappa_score(a, b)
    idx = [np.flatnonzero(ex == e) for e in EXAMS]
    bs = []
    for _ in range(B):
        i = np.concatenate([RNG.choice(j, len(j)) for j in idx])
        bs.append(cohen_kappa_score(a[i], b[i]))
    return k, *np.nanpercentile(bs, [2.5, 97.5])


say("# Camera-ready analyses (auto-generated by camera_ready.py)\n")
say("## 1. Agreement on collapsed schemes (κ [95% CI, items resampled within exam]; exact agreement)\n")
rows = []
for s1, s2 in PAIRS:
    s_ = df.dropna(subset=[BLOOM[s1], BLOOM[s2]])
    rec = {"pair": f"{s1} vs {s2}", "n": len(s_)}
    for sch, fn in SCHEMES.items():
        a, b = fn(s_[BLOOM[s1]].to_numpy(int)), fn(s_[BLOOM[s2]].to_numpy(int))
        k, lo, hi = kappa_strat_ci(a, b, s_.exam.to_numpy())
        rec[sch] = f"{k:.2f} [{lo:.2f}, {hi:.2f}]; {np.mean(a == b):.2f}"
    rows.append(rec)
say(pd.DataFrame(rows).set_index("pair").to_markdown())
say("\nShare placed at apply or above: " + ", ".join(f"{n} {(df[c] >= 2).mean():.2f}" for n, c in BLOOM.items()))
say("Share placed at remember: " + ", ".join(f"{n} {(df[c] == 0).mean():.2f}" for n, c in BLOOM.items()))

# ================================================================ 2. per-exam agreement
say("\n## 2. Per-exam agreement (six levels, unweighted κ; exact agreement)\n")
rows = []
for s1, s2 in PAIRS:
    rec = {"pair": f"{s1} vs {s2}"}
    for e in EXAMS:
        s_ = df[df.exam == e].dropna(subset=[BLOOM[s1], BLOOM[s2]])
        a, b = s_[BLOOM[s1]].astype(int), s_[BLOOM[s2]].astype(int)
        rec[e] = f"{cohen_kappa_score(a, b):.2f} ({np.mean(a == b):.2f})"
        if s1 == "Rater A" and s2 == "Gemini self" or s2 == "Gemini self":
            rec[e] += f", self higher {np.mean(b > a):.2f}"
    rows.append(rec)
say(pd.DataFrame(rows).set_index("pair").to_markdown())

# ================================================================ 3. two-stage bootstrap
LABELS = {"Gemini self difficulty": "llm_diff_i", "Fable instr. difficulty": "F_diff_i_n",
          "Fable bare difficulty": "F_diff_b_n", "Gemini cold difficulty": "G_diff_i_n",
          "Gemini cold bare difficulty": "G_diff_b_n",
          **{f"{n} Bloom": c for n, c in BLOOM.items()}}


def facility_boot(resample_students: bool, resample_items: bool):
    """One bootstrap draw: returns (row index array, facility array, within-exam pct rank array)."""
    rows, fac, rank = [], [], []
    for e in EXAMS:
        Xe = X[e][0]
        s = RNG.integers(0, Xe.shape[0], Xe.shape[0]) if resample_students else np.arange(Xe.shape[0])
        j = RNG.integers(0, Xe.shape[1], Xe.shape[1]) if resample_items else np.arange(Xe.shape[1])
        p = Xe[s][:, j].mean(0)
        rows.append(np.asarray(IDX[e])[j]); fac.append(p)
        rank.append(stats.rankdata(p) / len(p))
    return np.concatenate(rows), np.concatenate(fac), np.concatenate(rank)


def spearman_nan(x, y):
    ok = ~np.isnan(x)
    if np.unique(x[ok]).size < 2:
        return np.nan
    return stats.spearmanr(x[ok], y[ok]).statistic


say("\n## 3. Within-exam Spearman ρ between label and facility, with two kinds of 95% interval\n")
say("items: items resampled within exam (as in the submitted version, stratified); "
    "students+items: students resampled within exam, facility recomputed, then items resampled within exam.\n")
draws = {"items": [facility_boot(False, True) for _ in range(B)],
         "students+items": [facility_boot(True, True) for _ in range(B)]}
rows = []
for name, col in LABELS.items():
    v = df[col].to_numpy(float)
    rho = spearman_nan(v, df.p_rank_in_exam.to_numpy())
    rec = {"label": name, "ρ within": f"{rho:.2f}"}
    for kind, dr in draws.items():
        bs = [spearman_nan(v[r], rk) for r, _, rk in dr]
        lo, hi = np.nanpercentile(bs, [2.5, 97.5])
        rec[kind] = f"[{lo:.2f}, {hi:.2f}]"
    # per exam, with the student+item interval
    for e in EXAMS:
        s_ = df[df.exam == e]
        rho_e = spearman_nan(s_[col].to_numpy(float), s_.p.to_numpy())
        rec[e] = f"{rho_e:.2f}"
    rows.append(rec)
say(pd.DataFrame(rows).set_index("label").to_markdown())

# per-exam intervals (students + items) for the difficulty labels
say("\nPer-exam ρ with students+items interval:")
for name in ["Gemini self difficulty", "Fable instr. difficulty", "Gemini cold difficulty"]:
    col = LABELS[name]; parts = []
    for e in EXAMS:
        v_all = df[col].to_numpy(float)
        bs = []
        for r, f, _ in draws["students+items"]:
            m = df.exam.to_numpy()[r] == e
            bs.append(spearman_nan(v_all[r][m], f[m]))
        s_ = df[df.exam == e]
        parts.append(f"{e} {spearman_nan(s_[col].to_numpy(float), s_.p.to_numpy()):.2f} "
                     f"[{np.nanpercentile(bs, 2.5):.2f}, {np.nanpercentile(bs, 97.5):.2f}]")
    say(f"  {name}: " + "; ".join(parts))

# flagged items: difference in mean within-exam rank, students+items interval
fl = df.flag.to_numpy()
d0 = df.p_rank_in_exam[fl].mean() - df.p_rank_in_exam[~fl].mean()
bs = [rk[fl[r]].mean() - rk[~fl[r]].mean() for r, _, rk in draws["students+items"]]
bsf = [f[fl[r]].mean() - f[~fl[r]].mean() for r, f, _ in draws["students+items"]]
say(f"\nFlagged (n={fl.sum()}) minus other items: mean within-exam rank {d0:.2f} "
    f"[{np.nanpercentile(bs, 2.5):.2f}, {np.nanpercentile(bs, 97.5):.2f}]; mean facility "
    f"{df.p[fl].mean() - df.p[~fl].mean():.2f} [{np.nanpercentile(bsf, 2.5):.2f}, {np.nanpercentile(bsf, 97.5):.2f}] (students+items)")
say("  per exam facility flagged vs other: " + "; ".join(
    f"{e} {df.p[(df.exam == e) & fl].mean():.2f} vs {df.p[(df.exam == e) & ~fl].mean():.2f} (n flagged {((df.exam == e) & fl).sum()})" for e in EXAMS))

# ================================================================ 4. mixed logistic model (lme4, see camera_ready_glmm.R)
long = []
for e in EXAMS:
    Xe, Q, S = X[e]
    for si, s in enumerate(S):
        for qi, q in enumerate(Q):
            long.append({"y": int(Xe[si, qi]), "exam": e, "student": f"{e}:s{si + 1}", "item": f"{e}:{q}", "row": IDX[e][qi]})
long = pd.DataFrame(long)
for name, col in LABELS.items():
    long[col] = df[col].to_numpy(float)[long.row]
long.drop(columns="row").to_csv(OUT / "responses_long.csv", index=False)  # student ids replaced by s1..sN
say("\n## 4. Mixed logistic model: see out/camera_ready_glmm.txt (camera_ready_glmm.R)")

# ================================================================ 5. binomial uncertainty of facility
say("\n## 5. Binomial uncertainty of item facility (Wilson 95%)\n")
lo, hi = proportion_confint((df.p * df.n).round(), df.n, method="wilson")
w = hi - lo
say(f"Interval width: median {np.median(w):.2f}, range {w.min():.2f} to {w.max():.2f}. "
    f"Example: 9 of 12 correct (0.75) -> [{proportion_confint(9, 12, method='wilson')[0]:.2f}, {proportion_confint(9, 12, method='wilson')[1]:.2f}]; "
    f"12 of 12 -> [{proportion_confint(12, 12, method='wilson')[0]:.2f}, 1.00]")

# ================================================================ 6. KR-20
say("\n## 6. KR-20 and the flagged items\n")


def kr20(Xe):
    p = Xe.mean(0); vt = Xe.sum(1).var()
    return Xe.shape[1] / (Xe.shape[1] - 1) * (1 - (p * (1 - p)).sum() / vt)


for e in EXAMS:
    Xe, Q, S = X[e]
    bs = [kr20(Xe[RNG.integers(0, len(S), len(S))]) for _ in range(B)]
    fq = np.array([df.flag[i] for i in IDX[e]])
    keep = ~fq
    disc = df.disc[IDX[e]].to_numpy()
    say(f"  {e}: KR-20 {kr20(Xe):.2f} [{np.nanpercentile(bs, 2.5):.2f}, {np.nanpercentile(bs, 97.5):.2f}] (students resampled); "
        f"without the {fq.sum()} flagged items {kr20(Xe[:, keep]):.2f} ({keep.sum()} items); "
        f"only flagged items {kr20(Xe[:, fq]):.2f}; total-score SD {Xe.sum(1).std(ddof=1):.1f} of {len(Q)}; "
        f"mean item-rest r flagged {np.nanmean(disc[fq]):.2f} vs other {np.nanmean(disc[~fq]):.2f}")
fl_d, ot_d = df.disc[df.flag].dropna(), df.disc[~df.flag].dropna()
say(f"  All: item-rest r flagged {fl_d.mean():.2f} (n={len(fl_d)}, {df.disc[df.flag].isna().sum()} undefined) vs other "
    f"{ot_d.mean():.2f} (n={len(ot_d)}, {df.disc[~df.flag].isna().sum()} undefined); MWU p={stats.mannwhitneyu(fl_d, ot_d).pvalue:.3f}")
# instability of item-rest r: student bootstrap SE per item
ses = []
for e in EXAMS:
    Xe = X[e][0]
    bs = []
    for _ in range(500):
        s = RNG.integers(0, Xe.shape[0], Xe.shape[0]); Y = Xe[s]; tot = Y.sum(1)
        with np.errstate(invalid="ignore", divide="ignore"):
            bs.append([np.corrcoef(Y[:, j], tot - Y[:, j])[0, 1] if Y[:, j].std() > 0 else np.nan for j in range(Y.shape[1])])
    ses.extend(np.nanstd(np.array(bs), 0))
say(f"  Item-rest r bootstrap SE over students: median {np.nanmedian(ses):.2f}")

# ================================================================ 7. items self-labelled above apply that raters put low
say("\n## 7. Misc\n")
say(f"Items flagged by B: {df.flag.sum()}; rater-A level on them: " + str(df[df.flag].A_bloom.value_counts().to_dict()))

(OUT / "camera_ready.md").write_text("\n".join(md) + "\n")
