"""Hand-coded themes for the free-text annotator comments (100 comments: 97 by B, 3 by A).
Key: (exam, question_no, annotator) -> list of theme codes. Coded by the analysis
author from comments_full.txt; a comment can carry several codes. The Final Exam
block (43 comments by B) was coded 2026-09-01 after B completed the annotation."""
THEMES = {
    "distractors":  "one or more distractors implausible / nonsensical / excludable without domain knowledge",
    "giveaway":     "wording of the correct option gives the answer away",
    "recall_dep":   "answer hinges on recalling a specific statement from the course material / depends on how the topic was taught",
    "common_sense": "answerable by reading comprehension or common sense, without ML knowledge",
    "flaw":         "stem or key judged ambiguous, flawed or poor",
    "duplicate":    "item noted as identical or similar to one on another exam",
    "unfamiliar":   "annotator unfamiliar with the topic",
    "lower_bound":  "explicit reasoning that the item cannot be Evaluate/Analyze because alternatives are not defensible",
}
E, M, F = "Exam 2", "Midterm 3", "Final Exam"
CODES = {
    # ---- Final Exam (paper: Exam 3), rater B
    (F, 6, "B"): ["distractors"],
    (F, 8, "B"): ["distractors"],
    (F, 9, "B"): ["distractors"],
    (F, 10, "B"): ["flaw", "distractors"],
    (F, 12, "B"): ["distractors", "common_sense"],
    (F, 13, "B"): ["flaw", "distractors", "recall_dep"],
    (F, 15, "B"): ["flaw", "distractors"],
    (F, 16, "B"): ["distractors"],
    (F, 18, "B"): ["distractors"],
    (F, 19, "B"): ["distractors"],
    (F, 22, "B"): ["distractors", "flaw", "recall_dep"],
    (F, 23, "B"): ["distractors"],
    (F, 26, "B"): ["distractors"],
    (F, 29, "B"): ["distractors"],
    (F, 30, "B"): ["distractors", "flaw"],
    (F, 34, "B"): ["recall_dep"],
    (F, 40, "B"): ["distractors", "common_sense"],
    (F, 41, "B"): ["distractors"],
    (F, 42, "B"): ["distractors"],
    (F, 43, "B"): ["distractors"],
    (F, 44, "B"): ["distractors"],
    (F, 45, "B"): ["distractors"],
    (F, 46, "B"): ["distractors"],
    (F, 47, "B"): ["distractors"],
    (F, 48, "B"): ["distractors"],
    (F, 49, "B"): ["distractors"],
    (F, 51, "B"): ["distractors", "recall_dep"],
    (F, 52, "B"): ["distractors", "recall_dep"],
    (F, 54, "B"): ["distractors"],
    (F, 56, "B"): ["distractors"],
    (F, 57, "B"): ["distractors"],
    (F, 58, "B"): ["recall_dep", "distractors"],
    (F, 59, "B"): ["distractors"],
    (F, 60, "B"): ["distractors", "common_sense"],
    (F, 61, "B"): ["distractors"],
    (F, 62, "B"): ["distractors"],
    (F, 63, "B"): ["distractors", "flaw"],
    (F, 65, "B"): ["giveaway", "recall_dep"],
    (F, 66, "B"): ["distractors"],
    (F, 67, "B"): ["recall_dep"],
    (F, 68, "B"): ["distractors"],
    (F, 69, "B"): ["distractors", "recall_dep"],
    (F, 70, "B"): ["distractors"],
    # ---- Exam 2 (paper: Exam 1) and Midterm 3 (paper: Exam 2)
    (E, 3, "B"): ["recall_dep"],
    (E, 6, "B"): ["recall_dep"],
    (E, 7, "B"): ["recall_dep"],
    (E, 9, "B"): ["distractors", "lower_bound"],
    (E, 10, "B"): ["recall_dep", "giveaway"],
    (E, 12, "B"): ["recall_dep", "giveaway"],
    (E, 16, "B"): ["recall_dep", "flaw"],
    (E, 20, "B"): ["distractors", "lower_bound"],
    (E, 21, "B"): ["distractors", "giveaway"],
    (E, 22, "B"): ["distractors", "common_sense"],
    (E, 23, "B"): [],
    (E, 27, "B"): ["distractors", "common_sense"],
    (E, 32, "B"): ["distractors"],
    (E, 35, "B"): ["distractors"],
    (E, 37, "B"): ["flaw"],
    (E, 38, "B"): ["distractors", "common_sense"],
    (E, 39, "B"): ["distractors", "lower_bound"],
    (E, 40, "B"): ["distractors"],
    (E, 42, "A"): ["recall_dep"],
    (E, 42, "B"): ["distractors", "giveaway"],
    (E, 45, "B"): ["distractors", "flaw"],
    (E, 46, "A"): ["recall_dep"],
    (E, 46, "B"): ["distractors"],
    (E, 48, "B"): ["flaw"],
    (E, 49, "B"): ["distractors", "flaw", "lower_bound"],
    (E, 53, "B"): ["distractors"],
    (M, 1, "B"): ["distractors"],
    (M, 6, "B"): ["distractors", "recall_dep"],
    (M, 7, "A"): ["recall_dep"],
    (M, 8, "B"): ["distractors"],
    (M, 11, "B"): ["distractors", "recall_dep", "lower_bound"],
    (M, 13, "B"): ["distractors"],
    (M, 14, "B"): ["distractors"],
    (M, 15, "B"): ["distractors"],
    (M, 16, "B"): ["distractors"],
    (M, 24, "B"): ["distractors"],
    (M, 25, "B"): ["unfamiliar"],
    (M, 26, "B"): ["unfamiliar"],
    (M, 27, "B"): ["distractors", "common_sense"],
    (M, 28, "B"): ["distractors", "common_sense"],
    (M, 29, "B"): ["distractors", "common_sense"],
    (M, 30, "B"): ["distractors", "common_sense"],
    (M, 32, "B"): ["distractors", "common_sense", "unfamiliar"],
    (M, 34, "B"): ["distractors", "unfamiliar"],
    (M, 35, "B"): ["distractors"],
    (M, 36, "B"): ["distractors", "common_sense"],
    (M, 37, "B"): ["distractors"],
    (M, 38, "B"): ["recall_dep"],
    (M, 45, "B"): ["distractors", "flaw"],
    (M, 48, "B"): ["duplicate"],
    (M, 49, "B"): ["duplicate"],
    (M, 50, "B"): ["duplicate"],
    (M, 51, "B"): ["duplicate"],
    (M, 52, "B"): ["duplicate"],
    (M, 54, "B"): ["distractors"],
    (M, 62, "B"): ["duplicate"],
    (M, 63, "B"): ["distractors"],
}
